#include "state.h"
#include <TFT_eSPI.h>
#include <WiFi.h>
static TFT_eSPI screen;static constexpr uint8_t PAGE_COUNT=4;
static void text(const String&v,int x,int y,uint16_t c=TFT_WHITE,int f=2){screen.setTextColor(c,TFT_BLACK);screen.drawString(v,x,y,f);}static String uptime(){uint32_t s=millis()/1000;return String(s/86400)+"d "+String((s%86400)/3600)+"h "+String((s%3600)/60)+"m";}static String shortValue(const String&v){if(v.length()<19)return v;return v.substring(0,8)+"..."+v.substring(v.length()-6);}static bool fresh(){return state.connected&&(uint32_t)(millis()-state.lastSync)<40000&&WiFi.status()==WL_CONNECTED;}
static void header(const String&t,uint8_t p){text("IMO",8,5,TFT_CYAN);text(t,66,5);text(state.revoked?"REVOKED":fresh()?"ONLINE":"OFFLINE",220,5,fresh()?TFT_GREEN:TFT_ORANGE);text(String(p+1)+"/"+String(PAGE_COUNT),292,5,TFT_DARKGREY,1);screen.drawFastHLine(8,27,304,TFT_DARKGREY);}static void row(int y,const String&l,const String&v,uint16_t c=TFT_WHITE){text(l,14,y,TFT_LIGHTGREY);text(v,142,y,c);}static void centered(const String&v,int y,uint16_t c=TFT_WHITE,int f=2){screen.setTextColor(c,TFT_BLACK);screen.drawCentreString(v,160,y,f);}
static void overview(uint8_t p){header("OVERVIEW",p);row(38,"UUID",shortValue(state.deviceId),TFT_CYAN);row(59,"USER",state.userName);row(80,"WALLET",state.connectedWalletUsdt+" USDT",TFT_CYAN);row(101,"DAILY AVG",state.dailyRevenueUsdt+" USDT",TFT_GREEN);row(122,"ACTIVITY",state.isStaking?"STAKING":"MINING",TFT_CYAN);row(143,"UPTIME",uptime());}
static void network(uint8_t p){header("NETWORK & POWER",p);row(42,"DOWNLOAD",state.downloadMbps+" Mbps",TFT_CYAN);row(66,"UPLOAD",state.uploadMbps+" Mbps",TFT_CYAN);row(90,"POWER",state.watts+" W",TFT_YELLOW);row(114,"ENERGY TODAY",state.energyTodayWh+" Wh",TFT_YELLOW);row(138,"SIGNAL",String(WiFi.RSSI())+" dBm");}
static void mining(uint8_t p){header("ACTIVITY",p);centered("CURRENT ACTIVITY",40,TFT_LIGHTGREY);centered(state.currency,61,TFT_CYAN,4);centered(state.isStaking?"PROOF OF STAKE (POS)":"PROOF OF WORK (POW)",99);centered(state.rate+(state.isStaking?" % APR":" MH/s"),120,TFT_CYAN);centered("+"+state.dailyUsdt+" USDT / ONLINE DAY",145,TFT_GREEN,1);}
static void wallet(uint8_t p){header("WALLET & REVENUE",p);centered("WITHDRAWAL ADDRESS",38,TFT_LIGHTGREY);centered("USDT - "+state.walletProtocol,59,TFT_CYAN);centered(state.walletAddress.length()?shortValue(state.walletAddress):"NOT SET",81);centered(state.connectedWalletUsdt+" USDT",105,TFT_CYAN,4);centered("AVERAGE DAILY REWARD",137,TFT_LIGHTGREY,1);centered("+"+state.dailyRevenueUsdt+" USDT",151,TFT_GREEN);}
void initializeDisplay(){screen.init();screen.setRotation(1);screen.fillScreen(TFT_BLACK);}void drawDisplay(){screen.fillScreen(TFT_BLACK);if(state.revoked){header("DEVICE",0);centered("CREDENTIAL REVOKED",70,TFT_RED);centered("CONTACT YOUR OPERATOR",105,TFT_LIGHTGREY);return;}if(!state.paired){header("PAIRING",0);centered("PAIR YOUR DEVICE",43);centered(state.pairingCode.length()?state.pairingCode:"------",75,TFT_CYAN,4);centered("ENTER CODE IN YOUR IMO DASHBOARD",130,TFT_LIGHTGREY,1);return;}if(!state.version){header("WAITING",0);centered("WAITING FOR OPERATOR",68);centered("PUBLICATION",96,TFT_CYAN);return;}uint8_t p=(millis()/5000)%PAGE_COUNT;switch(p){case 0:overview(p);break;case 1:network(p);break;case 2:mining(p);break;default:wallet(p);}}
