import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { dateTime, getAdminOverview, money } from '@/lib/adminData';

export const dynamic = 'force-dynamic';

export default async function RewardsPage() {
  const { rewards } = await getAdminOverview();

  return (
    <div className="space-y-6">
      <div>
        <h1 className="font-space text-3xl font-semibold">Rewards</h1>
        <p className="mt-1 text-sm text-muted-foreground">Recent USDT earnings generated by mining, LLM work, exchange, and trading.</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="font-space">Reward Ledger</CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>User</TableHead>
                <TableHead>Source</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Created</TableHead>
                <TableHead className="text-right">Amount</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {rewards.map((reward) => (
                <TableRow key={reward.id}>
                  <TableCell>
                    <div className="font-medium">{reward.users?.email ?? 'Unknown user'}</div>
                    <div className="text-xs text-muted-foreground">{reward.users?.uid ?? reward.id}</div>
                  </TableCell>
                  <TableCell className="capitalize">{reward.source.replace('_', ' ')}</TableCell>
                  <TableCell>
                    <Badge variant={reward.status === 'pending' ? 'default' : 'secondary'}>
                      {reward.status}
                    </Badge>
                  </TableCell>
                  <TableCell>{dateTime(reward.created_at)}</TableCell>
                  <TableCell className="text-right font-mono">{money(reward.amount)}</TableCell>
                </TableRow>
              ))}
              {rewards.length === 0 && (
                <TableRow>
                  <TableCell colSpan={5} className="text-center text-muted-foreground">
                    No rewards yet.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
